htdocs/config/routes.rb
      get 'courses/:course_id/web_zip_exports/:id', action: :show
    end

    scope(controller: :grading_standards_api) do
      get 'courses/:course_id/grading_standards', action: :context_index
      get 'accounts/:account_id/grading_standards', action: :context_index
      get 'courses/:course_id/grading_standards/:grading_standard_id', action: :context_show
      get 'accounts/:account_id/grading_standards/:grading_standard_id', action: :context_show
      post 'accounts/:account_id/grading_standards', action: :create
      post 'courses/:course_id/grading_standards', action: :create
    end

    get '/crocodoc_session', controller: 'crocodoc_sessions', action: 'show', as: :crocodoc_session
    get '/canvadoc_session', controller: 'canvadoc_sessions', action: 'show', as: :canvadoc_session

    scope(controller: :grading_period_sets) do
      get 'accounts/:account_id/grading_period_sets', action: :index, as: :account_grading_period_sets
      post 'accounts/:account_id/grading_period_sets', action: :create
      patch 'accounts/:account_id/grading_period_sets/:id', action: :update, as: :account_grading_period_set
      delete 'accounts/:account_id/grading_period_sets/:id', action: :destroy
    end

    scope(controller: :grading_periods) do
      # FIXME: This route will be removed/replaced with CNVS-27101
      get 'accounts/:account_id/grading_periods', action: :index, as: :account_grading_periods

      get 'courses/:course_id/grading_periods', action: :index, as: :course_grading_periods
      get 'courses/:course_id/grading_periods/:id', action: :show, as: :course_grading_period
      patch 'courses/:course_id/grading_periods/batch_update',
            action: :batch_update, as: :course_grading_period_batch_update
      put 'courses/:course_id/grading_periods/:id', action: :update, as: :course_grading_period_update
      delete 'courses/:course_id/grading_periods/:id', action: :destroy, as: :course_grading_period_destroy
      delete 'accounts/:account_id/grading_periods/:id', action: :destroy, as: :account_grading_period_destroy

      patch 'grading_period_sets/:set_id/grading_periods/batch_update',
            action: :batch_update, as: :grading_period_set_periods_update
    end

    scope(controller: :usage_rights) do
      %w(course group user).each do |context|
        content_prefix = "#{context.pluralize}/:#{context}_id"
        put "#{content_prefix}/usage_rights", action: :set_usage_rights
        delete "#{content_prefix}/usage_rights", action: :remove_usage_rights
        get "#{content_prefix}/content_licenses", action: :licenses
      end
    end

    scope(controller: 'bookmarks/bookmarks') do
      get 'users/self/bookmarks/', action: :index, as: :bookmarks
      get 'users/self/bookmarks/:id', action: :show
      post 'users/self/bookmarks', action: :create
      delete 'users/self/bookmarks/:id', action: :destroy
      put 'users/self/bookmarks/:id', action: :update
    end

    scope(controller: :course_nicknames) do
      get 'users/self/course_nicknames', action: :index, as: :course_nicknames
      get 'users/self/course_nicknames/:course_id', action: :show
      put 'users/self/course_nicknames/:course_id', action: :update
      delete 'users/self/course_nicknames/:course_id', action: :delete
      delete 'users/self/course_nicknames', action: :clear
    end

    scope(controller: :shared_brand_configs) do
      post 'accounts/:account_id/shared_brand_configs', action: :create
      put 'accounts/:account_id/shared_brand_configs/:id', action: :update
      delete 'shared_brand_configs/:id', action: :destroy
    end

    scope(controller: :errors) do
      post "error_reports", action: :create
    end

    scope(controller: :jwts) do
      post 'jwts', action: :create
      post 'jwts/refresh', action: :refresh
    end

    scope(controller: :gradebook_settings) do
      put 'courses/:course_id/gradebook_settings', action: :update, as: :course_gradebook_settings_update
    end

    scope(controller: :announcements_api) do
      get 'announcements', action: :index, as: :announcements
    end

    scope(controller: :rubrics_api) do
      get 'accounts/:account_id/rubrics', action: :index, as: :account_rubrics
      get 'accounts/:account_id/rubrics/:id', action: :show
      get 'courses/:course_id/rubrics', action: :index, as: :course_rubrics
      get 'courses/:course_id/rubrics/:id', action: :show
      post 'courses/:course_id/rubrics', controller: :rubrics, action: :create
      put 'courses/:course_id/rubrics/:id', controller: :rubrics, action: :update
      delete 'courses/:course_id/rubrics/:id', controller: :rubrics, action: :destroy
    end

    scope(controller: :rubric_associations) do
      post 'courses/:course_id/rubric_associations', action: :create
      put 'courses/:course_id/rubric_associations/:id', action: :update
      delete 'courses/:course_id/rubric_associations/:id', action: :destroy
    end

    scope(controller: :rubric_assessment_api) do
      post 'courses/:course_id/rubric_associations/:rubric_association_id/rubric_assessments', controller: :rubric_assessments, action: :create
      put 'courses/:course_id/rubric_associations/:rubric_association_id/rubric_assessments/:id', controller: :rubric_assessments, action: :update
      delete 'courses/:course_id/rubric_associations/:rubric_association_id/rubric_assessments/:id', controller: :rubric_assessments, action: :destroy
    end

    scope(controller: 'master_courses/master_templates') do
      get 'courses/:course_id/blueprint_templates/:template_id', action: :show
      get 'courses/:course_id/blueprint_templates/:template_id/associated_courses', action: :associated_courses, as: :course_blueprint_associated_courses
      put 'courses/:course_id/blueprint_templates/:template_id/update_associations', action: :update_associations
      get 'courses/:course_id/blueprint_templates/:template_id/unsynced_changes', action: :unsynced_changes, as: :course_blueprint_unsynced_changes

      post 'courses/:course_id/blueprint_templates/:template_id/migrations', action: :queue_migration
      get 'courses/:course_id/blueprint_templates/:template_id/migrations', action: :migrations_index, as: :course_blueprint_migrations
      get 'courses/:course_id/blueprint_templates/:template_id/migrations/:id', action: :migrations_show
      get 'courses/:course_id/blueprint_templates/:template_id/migrations/:id/details', action: :migration_details

      put 'courses/:course_id/blueprint_templates/:template_id/restrict_item', action: :restrict_item

      get 'courses/:course_id/blueprint_subscriptions', action: :subscriptions_index, as: :course_blueprint_subscriptions
      get 'courses/:course_id/blueprint_subscriptions/:subscription_id/migrations', action: :imports_index, as: :course_blueprint_imports
      get 'courses/:course_id/blueprint_subscriptions/:subscription_id/migrations/:id', action: :imports_show
      get 'courses/:course_id/blueprint_subscriptions/:subscription_id/migrations/:id/details', action: :import_details
    end

    scope(controller: :late_policy) do
      get 'courses/:id/late_policy', action: :show
      post 'courses/:id/late_policy', action: :create
      patch 'courses/:id/late_policy', action: :update
    end

    scope(controller: :planner) do
      get 'planner/items', action: :index, as: :planner_items
      get 'users/:user_id/planner/items', action: :index, as: :user_planner_items
    end

    scope(controller: :planner_overrides) do
      get 'planner/overrides', action: :index, as: :planner_overrides
      get 'planner/overrides/:id', action: :show
      put 'planner/overrides/:id', action: :update
      post 'planner/overrides', action: :create
      delete 'planner/overrides/:id', action: :destroy
    end

    scope(controller: :planner_notes) do
      get 'planner_notes', action: :index, as: :planner_notes
      get 'planner_notes/:id', action: :show, as: :planner_notes_show
      put 'planner_notes/:id', action: :update
      post 'planner_notes', action: :create
      delete 'planner_notes/:id', action: :destroy
    end

    scope(controller: :content_shares) do
      post 'users/:user_id/content_shares', action: :create
      get 'users/:user_id/content_shares/sent', action: :index, defaults: { list: 'sent' }, as: :user_sent_content_shares
      get 'users/:user_id/content_shares/received', action: :index, defaults: { list: 'received' }, as: :user_received_content_shares
      get 'users/:user_id/content_shares/unread_count', action: :unread_count
      get 'users/:user_id/content_shares/:id', action: :show
      delete 'users/:user_id/content_shares/:id', action: :destroy
      post 'users/:user_id/content_shares/:id/add_users', action: :add_users
      put 'users/:user_id/content_shares/:id', action: :update
    end

    scope(:controller => :csp_settings) do
      %w(course account).each do |context|
        get "#{context.pluralize}/:#{context}_id/csp_settings", :action => :get_csp_settings
        put "#{context.pluralize}/:#{context}_id/csp_settings", :action => :set_csp_setting
      end
      put "accounts/:account_id/csp_settings/lock", :action => :set_csp_lock
      post "accounts/:account_id/csp_settings/domains", :action => :add_domain
      post "accounts/:account_id/csp_settings/domains/batch_create", :action => :add_multiple_domains
      delete "accounts/:account_id/csp_settings/domains", :action => :remove_domain
      get "accounts/:account_id/csp_log", action: :csp_log
    end

    scope(:controller => :context) do
      post 'media_objects', action: 'create_media_object', as: :create_media_object
    end

    scope(:controller => :media_objects) do
      put 'media_objects/:media_object_id', action: 'update_media_object', as: :update_media_object
    end

    scope(:controller => :media_tracks) do
      get 'media_objects/:media_object_id/media_tracks', action: 'index', as: :list_media_tracks

htdocs/app/controllers/login/shared.rb
#
# Copyright (C) 2015 - present Instructure, Inc.
#
# This file is part of Canvas.
#
# Canvas is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3 of the License.
#
# Canvas is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

module Login::Shared
  include FullStoryHelper

  def reset_session_for_login
    reset_session_saving_keys(:return_to,
                              :oauth,
                              :oauth2,
                              :confirm,
                              :enrollment,
                              :expected_user_id,
                              :masquerade_return_to,
                              :oauth2_nonce)
  end

  def successful_login(user, pseudonym, otp_passed = false)
    reset_authenticity_token!
    Auditors::Authentication.record(pseudonym, 'login')

    # Since the user just logged in, we'll reset the context to include their info.
    setup_live_events_context
    # TODO: Only send this if the current_pseudonym's root account matches the current root
    # account?
    Canvas::LiveEvents.logged_in(session, user, pseudonym)

    otp_passed ||= user.validate_otp_secret_key_remember_me_cookie(cookies['canvas_otp_remember_me'], request.remote_ip)
    unless otp_passed
      mfa_settings = user.mfa_settings(pseudonym_hint: @current_pseudonym)
      if (user.otp_secret_key && mfa_settings == :optional) ||
          mfa_settings == :required
        session[:pending_otp] = true
        return redirect_to otp_login_url
      end
    end

    # ensure the next page rendered includes an instfs pixel to log them in
    # there
    session.delete(:shown_instfs_pixel)

    if pseudonym.account_id != (@real_domain_root_account || @domain_root_account).id
      flash[:notice] = t("You are logged in at %{institution1} using your credentials from %{institution2}",
                         institution1: (@real_domain_root_account || @domain_root_account).name,
                         institution2: pseudonym.account.name)
    end

    if pseudonym.account_id == Account.site_admin.id && Account.site_admin.delegated_authentication?
      cookies['canvas_sa_delegated'] = {
          :value => '1',
          :domain => remember_me_cookie_domain,
          :httponly => true,
          :secure => CanvasRails::Application.config.session_options[:secure]
      }
    end
    session[:require_terms] = true if @domain_root_account.require_acceptance_of_terms?(user)
    @current_user = user

    fullstory_init(@domain_root_account, session)

    respond_to do |format|
      if (oauth = session[:oauth2])
        provider = Canvas::Oauth::Provider.new(oauth[:client_id], oauth[:redirect_uri], oauth[:scopes], oauth[:purpose])
        return redirect_to Canvas::Oauth::Provider.confirmation_redirect(self, provider, user)
      elsif session[:course_uuid] && user &&
          (course = Course.where(uuid: session[:course_uuid], workflow_state: "created").first)
        claim_session_course(course, user)
        format.html { redirect_to(course_url(course, :login_success => '1')) }
      elsif session[:confirm]
        format.html do
          redirect_to(registration_confirmation_path(session.delete(:confirm),
                                                     enrollment: session.delete(:enrollment),
                                                     login_success: 1,
                                                     confirm: (user.id == session.delete(:expected_user_id) ? 1 : nil)))
        end
      else
        # the URL to redirect back to is stored in the session, so it's
        # assumed that if that URL is found rather than using the default,
        # they must have cookies enabled and we don't need to worry about
        # adding the :login_success param to it.
        format.html { redirect_back_or_default(dashboard_url(:login_success => '1')) }
      end
      format.json { render :json => pseudonym.as_json(:methods => :user_code), :status => :ok }
    end
  end

  def logout_current_user
    reset_authenticity_token!
    Auditors::Authentication.record(@current_pseudonym, 'logout')
    Canvas::LiveEvents.logged_out
    Lti::LogoutService.queue_callbacks(@current_pseudonym)
    super
  end

  def forbid_on_files_domain
    if HostUrl.is_file_host?(request.host_with_port)
      reset_session
      return redirect_to dashboard_url(:host => HostUrl.default_host)
    end
    true
  end

  include PseudonymSessionsController
  def remember_me_cookie_domain
    otp_remember_me_cookie_domain
  end

  def delegated_auth_redirect_uri(uri)
    uri
  end
end

htdocs/app/views/shared/_account_options.html.erb
<%
# Copyright (C) 2011 - present Instructure, Inc.
#
# This file is part of Canvas.
#
# Canvas is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3 of the License.
#
# Canvas is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.
%>

<% indent ||= 0 %>
<option value="<%= account.id %>" <%= "selected" if @context && @context.account_id == account.id %>><%= raw("&nbsp;" * indent) %><%= account.name %></option>
<% account.sub_accounts.order(Account.best_unicode_collation_key('name')).active.each do |a| %>
  <%= render :partial => "shared/account_options", :locals => {:account => a, :indent => indent + 2} %>
<% end %>

htdocs/app/views/shared/_assignment_rubric_dialog.html.erb
<%
# Copyright (C) 2011 - present Instructure, Inc.
#
# This file is part of Canvas.
#
# Canvas is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3 of the License.
#
# Canvas is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.
%>

<div id="rubrics" class="rubric_dialog" style="display: none; margin-bottom: 10px;">
  <% if @assignment.rubric_association && @assignment.rubric_association.rubric %>
    <%= render :partial => "shared/rubric", :object => @assignment.rubric_association.rubric,
        :locals => {:association => @assignment,
            :rubric_association => @assignment.rubric_association,
            :editable => can_do(@assignment, @current_user, :update),
            :has_assessments => !@assignment.rubric_association.rubric_assessments.empty?, :edit_view => true} %>
  <% end %>
  <div style="display: none;" id="rubric_parameters">
    <input type="hidden" name="rubric_association[association_type]" value="Assignment"/>
    <input type="hidden" name="rubric_association[association_id]" value="<%= @assignment.id %>"/>
    <input type="hidden" name="rubric_association[purpose]" value="grading"/>
  </div>
  <div class="assignment_points_possible" style="display: none;"><%= round_if_whole(@assignment.points_possible) %></div>
  <% if can_do(@assignment, @current_user, :update) %>
    <%= render :partial => "shared/rubric_dialog", :locals => {:assignment => @assignment, :rubric => @assignment.rubric_association && @assignment.rubric_association.rubric} %>
  <% end %>
  <%= render :partial => "shared/rubric_criterion_dialog" %>
  <%= render :partial => "shared/find_outcome" %>
  <%= render :partial => "shared/rubric", :object => nil, :locals => {:association => @assignment, :editable => can_do(@assignment, @current_user, :update), :has_assessments => false, :edit_view => true} %>
  <% if can_do(@assignment, @current_user, :update) %>
    <div style="text-align: center; font-size: 1.2em; margin-top: 10px; display: none;">
      <a href="<%= context_url(@context, :context_rubrics_url) %>" class="add_rubric_link rubric" style="<%= hidden if @assignment.rubric_association %>"><%= t 'links.assign_rubric', "Assign Rubric" %></a>
    </div>
  <% end %>
  <a href="#" class="btn add_rubric_link" style="margin-top: 20px; <%= hidden if @assignment && @assignment.rubric_association %>"><%= image_tag "rubric.png", :alt => '' %> <%= t 'links.add_rubric', "Add Rubric" %></a>
</div>

<script>
  window.ENV = window.ENV || {};
  window.ENV.ROOT_OUTCOME_GROUP = <%= raw @root_outcome_group %>;
  var event = document.createEvent('Event');
  event.initEvent('rubricEditDataReady', true, true);
  document.dispatchEvent(event)
</script>

htdocs/app/views/shared/_auth_type_icon.html.erb
<%
# Copyright (C) 2015 - present Instructure, Inc.
#
# This file is part of Canvas.
#
# Canvas is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3 of the License.
#
# Canvas is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.
%>

<span class="ic-Login_icon-sso ic-Login_icon-sso--icon-only" role="presentation">
  <%= svg_icon "#{auth_type}" %>
</span>
<% if with_login_text %>
  <span class="ic-Login__sso-button__title ic-Login__sso-button__title--<%= auth_type %>">
    <%= with_login_text %>
  </span>
<% end %>
<% if sr_message.present? %>
  <span class="screenreader-only"><%= sr_message %><span>
<% end %>

htdocs/app/views/shared/_canvas-user-nav.erb
<%
# Copyright (C) 2014 - present Instructure, Inc.
#
# This file is part of Canvas.
#
# Canvas is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3 of the License.
#
# Canvas is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.
%>

<div id="topbar" role="navigation" aria-label="<%= t('navigation.user_menu', 'User Menu') %>">
  <% if (identity = (yield :identity).presence) %>
    <%= identity %>
  <% else %>
    <%= render(:partial => 'shared/identity') %>
  <% end %>
</div>

htdocs/app/views/shared/_current_enrollment.html.erb
<%
# Copyright (C) 2011 - present Instructure, Inc.
#
# This file is part of Canvas.
#
# Canvas is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3 of the License.
#
# Canvas is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.
%>

<% dashboard ||= false %>
<% is_current_term ||= false %>
<% # only show updated css in unpublished, current enrollments with FF enabled %>
<% unpublished_course_redesign =
  (current_enrollment.course.created? || current_enrollment.course.claimed?) &&
  is_current_term &&
  @domain_root_account.feature_enabled?(:unpublished_courses)
%>
<% unless dashboard %>
  <tr class="course-list-table-row <%='course-list-unpublished-course-row' if unpublished_course_redesign %>">
<% end %>
<% if current_enrollment.workflow_state == "invited" && !current_enrollment.inactive? %>
  <div class="<%= dashboard ? 'communication_message dashboard_notification alert alert-info' : 'reminder' %>">
    <h2><a href="<%= course_path(current_enrollment.course_id, :invitation => current_enrollment.uuid) %>"><%= current_enrollment.long_name %></a></h2>
    <div class="body">
      <%=  render :partial => 'shared/invitation', :object => current_enrollment %>
    </div>
  </div>
<% else %>
  <% show_link = [:active, :invited, :accepted, :completed].include?(current_enrollment.state_based_on_date) && (!current_enrollment.course.unpublished? || current_enrollment.admin?) %>
      <% if @show_star_column %>
      <td class="course-list-star-column">
      <% favorite_course = @favorite_course_ids.include?(current_enrollment.course_id) %>
      <% past_course = enrollments_for_index(:past).include? current_enrollment %>
      <% favorite_past_course = past_course && favorite_course %>
      <% tooltip_message = t('nonfavorited_tooltip', "Click to add to the courses menu.") if !favorite_course %>
      <% tooltip_message = t("This course cannot be added to the courses menu at this time.") if (!show_link || past_course) %>
      <% tooltip_message = t('favorited_tooltip', "Click to remove from the courses menu.") if favorite_course || favorite_past_course %>
        <span
          class="<%= "course-list-favorite-course" if favorite_course %> <%= "course-list-not-favoritable disabled" if (!show_link || favorite_past_course) %> <%= "course-list-favoritable" if show_link %>"
          data-tooltip="bottom"
          title="<%= tooltip_message %>"
          role="button"
          tabindex="0"
          data-course-id="<%= current_enrollment.course_id %>"
          <% if (show_link && (favorite_past_course || !(past_course && !favorite_course))) %>
              <%= "data-favorite-url=#{api_v1_add_favorite_course_url(current_enrollment.course_id)}" %>
          <% end %>
        >
          <i class="<%= "course-list-favorite-icon #{favorite_course ? "icon-star" : "icon-star-light"}" %>"></i>
          <span id="course_list_screenreader_message_<%= current_enrollment.course_id %>" class="screenreader-only">
            <%= tooltip_message %>
          </span>
        </span>
      </td>
      <% end %>

      <% course_color = @current_user.custom_colors["course_#{current_enrollment.course_id}"] %>
      <td class="course-list-course-title-column
        <%= "course-list-no-left-border" if @show_star_column %>
        <%= "course-list-not-favoritable" unless @show_star_column %>">
        <% if course_color.present? %>
          <span aria-hidden="true" class="course-color-block" style="<%= "color: #{course_color};" %>" ></span>
        <% end %>
        <% if show_link %><a href="<%= course_path(current_enrollment.course_id) %>" title="<%= current_enrollment.course.name %>"><% end %>
        <span class="name">
          <%= current_enrollment.course.name %>
        </span>
        <% if show_link %></a>
        <% end %>
      </td>

      <td class="course-list-no-left-border course-list-nickname-column">
        <%= current_enrollment.course.nickname_for(@current_user, nil) %>
      </td>

      <td class="course-list-no-left-border course-list-term-column">
      <% if current_enrollment.course.enrollment_term.default_term? %>
        <span class="screenreader-only"><%= current_enrollment.course.enrollment_term.name %></span>
      <% else %>
        <%= current_enrollment.course.enrollment_term.name %>
      <% end %>
      </td>

      <td class="course-list-no-left-border course-list-enrolled-as-column">
        <%= current_enrollment.readable_role_name %>
      </td>

      <td class="course-list-no-left-border course-list-published-column ">
        <% if current_enrollment.course.created? || current_enrollment.course.claimed? %>
            <span
              class="<%= 'course-list-unpublished-course' if unpublished_course_redesign %>"
              data-tooltip
              title="<%= t('unpublished_course_tooltip', "This course has not been published. Students should contact the course instructor for access.") %>">
              <%= t('unpublished_course', "No") %>
            </span>
             <span class="screenreader-only"><%= t('unpublished_course_tooltip', "This course has not been published. Students should contact the course instructor for access.") %></span>
        <% else %>
            <span data-tooltip title="<%= t('published_course_tooltip', "This course has been published.") %>"><%= t('published_course', "Yes") %></span>
             <span class="screenreader-only"><%= t('published_course_tooltip', "This course has been published.") %></span>
        <% end %>
      </td>

<% end %>
<% unless dashboard %>
  </tr>
<% end %>

htdocs/app/views/shared/_dashboard_invitation.html.erb
<%
# Copyright (C) 2012 - present Instructure, Inc.
#
# This file is part of Canvas.
#
# Canvas is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3 of the License.
#
# Canvas is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.
%>

<% dashboard_invitation ||= nil %>
<% invitation = dashboard_invitation %>
<div class="ic-notification ic-notification--success">
  <div class="ic-notification__icon" role="presentation">
    <i class="icon-invitation"></i>
    <span class="screenreader-only">
      <%= accessible_message_icon_text("invitation") %>
    </span>
  </div>
  <div class="ic-notification__content">
    <div class="ic-notification__message notification_message">
      <%=
        mt(:invitation_text, "You have been invited to join [%{course}](%{link_to_course}) as %{enrollment_type_with_indefinite_article}", {
          :course => invitation.long_name,
          :link_to_course => course_path(invitation.course_id, :invitation => invitation.uuid),
          :enrollment_type_with_indefinite_article => Enrollment.type_with_indefinite_article(invitation.type).downcase
        })
      %>
    </div>
    <div class="ic-notification__actions">
      <%= form_tag course_enrollment_invitation_path(invitation.course_id) do %>
        <input type="hidden" name="invitation" value="<%= invitation.uuid %>" />
        <button type="submit" name="reject" class="Button Button--small"><%= t('buttons.decline', 'Decline') %></button>
        <button type="submit" name="accept" class="Button Button--small Button--success"><%= t('buttons.accept', 'Accept') %></button>
      <% end %>
    </div>
  </div>
</div>