htdocs/config/routes.rb
#
# Copyright (C) 2011 - present Instructure, Inc.
#
# This file is part of Canvas.
#
# Canvas is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3 of the License.
#
# Canvas is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

full_path_glob = '(/*full_path)'

# allow plugins to prepend routes
Dir["{gems,vendor}/plugins/*/config/pre_routes.rb"].each { |pre_routes|
  load pre_routes
}

CanvasRails::Application.routes.draw do
  post "/api/graphql", to: "graphql#execute"
  get 'graphiql', to: 'graphql#graphiql'

  resources :submissions, only: [] do
    resources :submission_comments, path: :comments, only: :index, defaults: { format: :pdf }
    resources :docviewer_audit_events, only: [:create], constraints: { format: :json }
  end
  resources :submission_comments, only: [:update, :destroy]

  resources :epub_exports, only: [:index]

  get 'inbox' => 'context#inbox'
  get 'oauth/redirect_proxy' => 'oauth_proxy#redirect_proxy'

  get 'conversations/unread' => 'conversations#index', as: :conversations_unread, redirect_scope: 'unread'
  get 'conversations/starred' => 'conversations#index', as: :conversations_starred, redirect_scope: 'starred'
  get 'conversations/sent' => 'conversations#index', as: :conversations_sent, redirect_scope: 'sent'
  get 'conversations/archived' => 'conversations#index', as: :conversations_archived, redirect_scope: 'archived'
  get 'conversations/find_recipients' => 'search#recipients'

  get 'search/recipients' => 'search#recipients'
  post 'conversations/mark_all_as_read' => 'conversations#mark_all_as_read'
  get 'conversations/batches' => 'conversations#batches', as: :conversation_batches
  resources :conversations, only: [:index, :show, :update, :create, :destroy] do
    post :add_recipients
    post :add_message
    post :remove_messages
  end

  post "/external_auth_observers/redirect_login" => 'login/external_auth_observers#redirect_login', as: :external_auth_validation

  # So, this will look like:
  # http://instructure.com/register/5R32s9iqwLK75Jbbj0
  match 'register/:nonce' => 'communication_channels#confirm', as: :registration_confirmation, via: [:get, :post]
  # deprecated
  get 'pseudonyms/:id/register/:nonce' => 'communication_channels#confirm', as: :registration_confirmation_deprecated
  post 'confirmations/:user_id/re_send(/:id)' => 'communication_channels#re_send_confirmation', as: :re_send_confirmation, id: nil
  get 'confirmations/:user_id/limit_reached(/:id)' => 'communication_channels#confirmation_limit_reached', as: :confirmation_limit_reached, id: nil
  match 'forgot_password' => 'pseudonyms#forgot_password', as: :forgot_password, via: [:get, :post]
  get 'pseudonyms/:pseudonym_id/change_password/:nonce' => 'pseudonyms#confirm_change_password', as: :confirm_change_password
  post 'pseudonyms/:pseudonym_id/change_password/:nonce' => 'pseudonyms#change_password', as: :change_password

  # callback urls for oauth authorization processes
  get 'oauth' => 'users#oauth'
  get 'oauth_success' => 'users#oauth_success'

  get 'mr/:id' => 'info#message_redirect', as: :message_redirect
  get 'help_links' => 'info#help_links'

  # This is a debug route that makes working on error pages easier
  get 'test_error' => 'info#test_error' unless Rails.env.production?

  concern :question_banks do
    resources :question_banks do
      post :bookmark
      post :reorder
      get :questions
      post :move_questions
      resources :assessment_questions
    end
  end

  concern :groups do
    resources :groups, except: :edit
    resources :group_categories, only: [:create, :update, :destroy]
    get 'group_unassigned_members' => 'groups#unassigned_members'
  end

  resources :group_categories do
    member do
      post 'clone_with_name'
    end
  end

  concern :files do
    resources :files, :except => [:new] do
      get 'inline' => 'files#text_show', as: :text_inline
      get 'download' => 'files#show', download: '1'
      get 'download.:type' => 'files#show', as: :typed_download, download: '1'
      get 'preview' => 'files#show', preview: '1'
      post 'inline_view' => 'files#show', inline: '1'
      get 'contents' => 'files#attachment_content', as: :attachment_content
      get 'file_preview' => 'file_previews#show'
      collection do
        get "folder#{full_path_glob}" => 'files#react_files', format: false
        get "search" => 'files#react_files', format: false
        get :quota
        post :reorder
      end
      get ':file_path' => 'files#show_relative', as: :relative_path, file_path: /.+/ #needs to stay below react_files route
    end
  end

  concern :file_images do
    get 'images' => 'files#images'
  end

  concern :relative_files do
    get 'file_contents/:file_path' => 'files#show_relative', as: :relative_file_path, file_path: /.+/
  end

  concern :folders do
    resources :folders
  end

  concern :media do
    get 'media_download' => 'users#media_download'
  end

  concern :users do
    get 'users' => 'context#roster'
    get 'user_services' => 'context#roster_user_services'
    get 'users/:user_id/usage' => 'context#roster_user_usage', as: :user_usage
    get 'users/:id' => 'context#roster_user', as: :user
  end

  concern :announcements do
    resources :announcements
    post 'announcements/external_feeds' => 'announcements#create_external_feed'
    delete 'announcements/external_feeds/:id' => 'announcements#destroy_external_feed', as: :announcements_external_feed
  end

  concern :discussions do
    resources :discussion_topics, only: [:index, :new, :show, :edit, :destroy]
    get 'discussion_topics/:id/:extras' => 'discussion_topics#show', as: :map, extras: /.+/
    resources :discussion_entries
  end

  concern :pages do
    resources :wiki_pages, path: :pages, except: [:update, :destroy, :new], constraints: { id: %r{[^\/]+} } do
      get 'revisions' => 'wiki_pages#revisions', as: :revisions
    end

    get 'wiki' => 'wiki_pages#front_page', as: :wiki
    get 'wiki/:id' => 'wiki_pages#show_redirect', id: /[^\/]+/
    get 'wiki/:id/revisions' => 'wiki_pages#revisions_redirect', id: /[^\/]+/
    get 'wiki/:id/revisions/:revision_id' => 'wiki_pages#revisions_redirect', id: /[^\/]+/
  end

  concern :conferences do
    resources :conferences do
      # rubocop:disable SymbolArray
      match :join, via: [:get, :post]
      match :close, via: [:get, :post]
      match :recording, via: [:get]
      match :recording, via: [:delete], to: 'conferences#delete_recording', as: :delete_recording
      # rubocop:enable SymbolArray
      get :settings
    end
  end

  get '/courses/:course_id/gradebook2', to: redirect('/courses/%{course_id}/gradebook')

  # There are a lot of resources that are all scoped to the course level
  # (assignments, files, wiki pages, user lists, forums, etc.).  Many of
  # these resources also apply to groups and individual users.  We call
  # courses, users, groups, or even accounts in this setting, "contexts".
  # There are some helper methods like the before_filter :get_context in application_controller
  # and the application_helper method :context_url to make retrieving
  # these contexts, and also generating context-specific urls, easier.
  resources :courses do
    # DEPRECATED
    get 'self_enrollment/:self_enrollment' => 'courses#self_enrollment', as: :self_enrollment
    post 'self_unenrollment/:self_unenrollment' => 'courses#self_unenrollment', as: :self_unenrollment
    post :unconclude
    get :students
    get 'observer_pairing_codes.csv', action: :observer_pairing_codes_csv, as: 'observer_pairing_codes'
    post :enrollment_invitation
    # this needs to come before the users concern, or users/:id will preempt it
    get 'users/prior' => 'context#prior_users', as: :prior_users
    concerns :users
    get :statistics
    delete 'unenroll/:id' => 'courses#unenroll_user', as: :unenroll
    post 'move_enrollment/:id' => 'courses#move_enrollment', as: :move_enrollment
    delete 'unenroll/:id.:format' => 'courses#unenroll_user', as: :formatted_unenroll
    post 'limit_user_grading/:id' => 'courses#limit_user', as: :limit_user_grading
    delete 'conclude_user/:id' => 'courses#conclude_user', as: :conclude_user_enrollment
    post 'unconclude_user/:id' => 'courses#unconclude_user', as: :unconclude_user_enrollment
    resources :sections, except: [:index, :edit, :new] do
      get 'crosslist/confirm/:new_course_id' => 'sections#crosslist_check', as: :confirm_crosslist
      post :crosslist
      delete 'crosslist' => 'sections#uncrosslist', as: :uncrosslist
    end

    get 'undelete' => 'context#undelete_index', as: :undelete_items
    post 'undelete/:asset_string' => 'context#undelete_item', as: :undelete_item

    get "settings#{full_path_glob}", action: :settings
    get :settings
    get 'details' => 'courses#settings'
    post :re_send_invitations
    post :enroll_users
    post :link_enrollment
    post :update_nav
    resource :gradebook do
      get 'submissions_upload/:assignment_id' => 'gradebooks#show_submissions_upload', as: :show_submissions_upload
      post 'submissions_upload/:assignment_id' => 'gradebooks#submissions_zip_upload', as: :submissions_upload

      collection do
        get :change_gradebook_version
        get :blank_submission
        get :final_grade_overrides
        get :speed_grader
        post :speed_grader_settings
        get :history
        post :update_submission
        post :change_gradebook_column_size
        post :save_gradebook_column_order
        get :user_ids
        get :grading_period_assignments
      end
    end

htdocs/app/views/layouts/_fixed_bottom.html.erb
<%
# Copyright (C) 2012 - present Instructure, Inc.
#
# This file is part of Canvas.
#
# Canvas is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3 of the License.
#
# Canvas is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.
%>

<div id="fixed_bottom">
  <% if @fixed_warnings.present? %>
    <% @fixed_warnings.each_with_index do |warning, index| %>
      <div id="element_toggler_<%= index %>" class="fixed_warning" aria-expanded="true" role="banner" aria-label="<%= t("Warning") %>">
        <i class=<%= "icon-#{warning[:icon]}" %>></i>
        <b><%= warning[:title] %></b>
        <div style="float: <%= direction('right') %>;">
          <%= warning[:message] %>
          <button class="element_toggler Button--icon-action" aria-controls="element_toggler_<%= index %>" >
            <i class="icon-x" aria-hidden="true"></i>
            <span class="screenreader-only"><%= t("Close warning") %></span>
          </button>
        </div>
      </div>
    <% end %>
  <% end %>
<% if @current_user && @real_current_user && @real_current_user != @current_user %>
  <% if @current_user.fake_student? %>
    <div id="masquerade_bar" class="ic-alert-masquerade-student-view">
      <% student_view_course = @current_user.all_courses.first %>
      <div class="ic-alert-masquerade-student-view-module ic-alert-masquerade-student-view-module--header">
        <div class="ic-image-text-combo">
          <i class="icon-student-view"></i>
          <div class="ic-image-text-combo__text"><%= t('student_view.warning_title', "You are currently logged into Student View") %></div>
        </div>
      </div>
      <div class="button-explanation ic-alert-masquerade-student-view-module ic-alert-masquerade-student-view-module--description">
        <%= t('student_view.reset_explanation', "Resetting the test student will clear all history for this student, allowing you to view the course as a brand new student.") %>
      </div>
      <div class="buttons ic-alert-masquerade-student-view-module ic-alert-masquerade-student-view-module--buttons">
        <%= link_to t('student_view.reset', "Reset Student"), course_test_student_path(student_view_course), 'data-method' => :delete, :rel => 'nofollow', :class => 'Button reset_test_student'%>
        <%= link_to t('student_view.leave', "Leave Student View"), course_student_view_path(student_view_course), 'data-method' => :delete, :rel => 'nofollow', :class => 'Button leave_student_view'%>
      </div>
    </div>
  <% else %>
    <div id="masquerade_bar" class="ic-alert-masquerade-student-view">
      <div class="ic-alert-masquerade-student-view-module ic-alert-masquerade-student-view-module--header">
        <div class="ic-image-text-combo">
          <% if service_enabled?(:avatars) %>
            <div class="masquerading_avatar">
              <%= avatar(@current_user, url: nil) %>
            </div>
          <% end %>
          <div class="ic-image-text-combo__text">
            <%= t("You are currently acting as %{user_name}", :user_name => @current_user.short_name) %>
          </div>
        </div>
      </div>
      <div class="buttons ic-fixed-bottom-module ic-fixed-bottom-module--buttons">
        <%= link_to t("Stop Acting as User"), user_masquerade_url(@real_current_user.id), 'data-method' => :post, :rel => 'nofollow', :class => 'Button stop_masquerading' %>
      </div>
    </div>
  <% end %>
<% end %>
</div>

htdocs/app/views/layouts/_foot.html.erb
<%= InstFS.login_pixel(logged_in_user, session, request.host_with_port) if logged_in_user && !@files_domain %>
<% js_bundle :inst_fs_service_worker if InstFS.service_worker_enabled? %>

<% if @js_env_data_we_need_to_render_later %>
  <script>
    Object.assign(
      ENV,
      <%= raw StringifyIds.recursively_stringify_ids(@js_env_data_we_need_to_render_later).to_json %>
    )
  </script>
<% end %>
<%= include_css_bundles %>
<%= include_js_bundles %>
<% unless @exclude_account_js %>
  <%= include_account_js %>
<% end %>

htdocs/app/views/layouts/_google_analytics_snippet.html.erb
<% if (google_analytics_key = Setting.get('google_analytics_key', nil)) &&
      @domain_root_account&.settings&.fetch(:enable_google_analytics, true)
%>
  <% dimensions = GoogleAnalyticsDimensions.calculate(
    domain_root_account: @domain_root_account,
    real_user: @real_current_user,
    user: @current_user,
  ) %>

  <script>
    window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
    ga('create', <%= raw(google_analytics_key.to_json) %>, 'auto');
    <% if @google_analytics_page_title %>
      ga('set', 'title', <%= raw(@google_analytics_page_title.to_json) %>);
    <% end %>
    <% if dimensions[:user_id] %>
      ga('set', 'userId', <%= dimensions.fetch(:user_id).to_json.html_safe %>);
    <% end %>
    ga('set', 'dimension1', <%= dimensions.fetch(:enrollments).to_json.html_safe %>);
    ga('set', 'dimension2', <%= dimensions.fetch(:admin).to_json.html_safe %>);
    ga('set', 'dimension3', <%= dimensions.fetch(:masquerading).to_json.html_safe %>);
    ga('set', 'dimension4', <%= dimensions.fetch(:org_type).to_json.html_safe %>);
    ga('send', 'pageview');
    (window.requestIdleCallback || window.setTimeout)(function(){
      var s=document.createElement('script'), m=document.getElementsByTagName('script')[0]
      s.async=1; s.src='https://www.google-analytics.com/analytics.js'
      m.parentNode.insertBefore(s,m)
    });
  </script>
<% end %>

htdocs/app/views/layouts/application.html.erb
<%
# Copyright (C) 2011 - present Instructure, Inc.
#
# This file is part of Canvas.
#
# Canvas is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3 of the License.
#
# Canvas is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.
%>
<%-
  css_bundle(:instructure_eportfolio) if @eportfolio_view === true
  css_bundle(:new_user_tutorials) if tutorials_enabled?
  css_bundle(:k6_theme) if @context.try(:feature_enabled?, :canvas_k6_theme)
  js_bundle(:navigation_header) unless @headers == false

  load_blueprint_courses_ui
  @has_content_notices = load_content_notices
  provide :head, include_common_stylesheets
  set_badge_counts_for(@context, @current_user, @current_enrollment) if @set_badge_counts
  js_env notices: flash_notices()
-%>
<%= render :partial => "layouts/head" %>
<%-
  left_side = nil
  left_side_custom = nil
  right_side = (yield :right_side).presence

  if @collapse_course_menu
    subnav_menu_text = t('Show Navigation Menu')
    subnav_menu_text = t('Show Courses Navigation Menu') if active_path?('/courses')
    subnav_menu_text = t('Show Account Navigation Menu') if active_path?('/profile')
    subnav_menu_text = t('Show Admin Navigation Menu') if active_path?('/accounts')
    subnav_menu_text = t('Show Groups Navigation Menu') if active_path?('/groups')
  else
    subnav_menu_text = t('Hide Navigation Menu')
    subnav_menu_text = t('Hide Courses Navigation Menu') if active_path?('/courses')
    subnav_menu_text = t('Hide Account Navigation Menu') if active_path?('/profile')
    subnav_menu_text = t('Hide Admin Navigation Menu') if active_path?('/accounts')
    subnav_menu_text = t('Hide Groups Navigation Menu') if active_path?('/groups')
  end

  @collapse_global_nav = @current_user.try(:collapse_global_nav?)
  @body_class_no_headers = @headers == false
  @show_embedded_chat = embedded_chat_visible
  @show_fixed_bottom = (@fixed_warnings.present? || (@real_current_user && @real_current_user != @current_user)) && (!@body_class_no_headers || @outer_frame)
  body_classes << "no-headers" if @body_class_no_headers
  unless (body_classes.include? "no-headers") || (@show_left_side == false)
    left_side = nil
    skip_for_streaming :left_side, except: ["eportfolios/show", "eportfolio_categories/show", "eportfolio_entries/show"] do
      left_side = (yield :left_side).presence
    end
    @show_left_side ||= (section_tabs.length > 0)
  end
  body_classes << "with-left-side" if @show_left_side
  body_classes << "course-menu-expanded" if body_classes.include?("with-left-side") && !@collapse_course_menu
  #we dont want to render a right side unless there is actually content in it.
  body_classes << "with-right-side" if right_side and not right_side.strip.empty?
  body_classes << "padless-content" if @padless
  body_classes << "with-embedded-chat" if @show_embedded_chat
  body_classes << 'with-fixed-bottom' if @show_fixed_bottom
  body_classes << 'pages' if controller.js_env[:WIKI_PAGE].present?
  body_classes << get_active_tab
  body_classes << 'Underline-All-Links__enabled' if @current_user && @current_user.feature_enabled?(:underline_all_links)
  body_classes << 'is-masquerading-or-student-view' if @real_current_user && @real_current_user != @current_user
  body_classes << 'primary-nav-expanded' unless @collapse_global_nav
  body_classes << 'primary-nav-transitions' if @collapse_global_nav
  # We probably want to consider doing this everywhere, all the time.
  body_classes << 'full-width' if @domain_root_account.try(:feature_enabled?, :new_user_tutorial)
  body_classes << "context-#{@context.asset_string}" if @context
  body_classes << "responsive_admin_settings" if !!@domain_root_account&.feature_enabled?(:responsive_admin_settings)
  body_classes << "responsive_awareness" if !!@domain_root_account&.feature_enabled?(:responsive_awareness)
  body_classes << "responsive_misc" if !!@domain_root_account&.feature_enabled?(:responsive_misc)
-%>
<body class="<%= (body_classes).uniq.join(" ") %>">
<%if @current_user && @real_current_user && @real_current_user != @current_user %>
  <div role="alert" class="screenreader-only">
    <% if @current_user.fake_student? %>
        <%= t("You are currently logged into Student View") %>
      <% else %>
        <%= t("You are currently acting as %{user_name}", :user_name => @current_user.short_name) %>
    <% end %>
  </div>
<% end %>
<%# Flash messages must be outside of #application or they won't work in screenreaders with modals open. %>
<%= render :partial => 'shared/static_notices' %>
<%= render :partial => 'shared/flash_notices' %>
<div id="application" class="ic-app">
  <%= render(:partial => 'shared/new_nav_header') unless @headers == false %>

  <div id="instructure_ajax_error_box">
    <div style="text-align: <%= direction('right') %>; background-color: #fff;"><a href="#" class="close_instructure_ajax_error_box_link"><%= t('links.close', 'Close') %></a></div>
    <iframe id="instructure_ajax_error_result" src="about:blank" style="border: 0;" title="<%= t('Error') %>"></iframe>
  </div>

  <div id="wrapper" class="ic-Layout-wrapper">
    <% if crumbs.length > 1 %>
      <div class="ic-app-nav-toggle-and-crumbs no-print">
        <% if @show_left_side %>
          <button type="button" id="courseMenuToggle" class="Button Button--link ic-app-course-nav-toggle" aria-live="polite" aria-label="<%= subnav_menu_text %>">
            <i class="icon-hamburger" aria-hidden="true"></i>
          </button>
          <div class="ic-app-crumbs">
        <% end %>
        <%= render_crumbs %>
        <% if @show_left_side %></div><% end %>
        <% if tutorials_enabled? %>
          <div class="TutorialToggleHolder"></div>
        <% end %>
      </div>
    <% end %>
    <div id="main" class="ic-Layout-columns">
      <% if !@body_class_no_headers %>
        <div class="ic-Layout-watermark"></div>
      <% end %>
      <% if @show_left_side %>
        <% if @no_left_side_list_view
            list_view_class = ''
          else
            list_view_class = 'list-view'
          end
        %>
        <div id="left-side"
          class="ic-app-course-menu <%= list_view_class %>"
          style="display: <%= @collapse_course_menu ? "none" : "block" %>"
          >
          <% if left_side %>
            <%= left_side %>
          <% else %>
            <% if @context && @context.is_a?(Group) && can_do(@context, @current_user, :manage) && @context.group_category %>
              <a class="al-trigger al-trigger--within-left-menu" href="#" data-popup-within="#wrapper">
                <%= t("Switch Group")%>
                <i class="icon-mini-arrow-down"></i>
              </a>
              <ul class="al-options">
                <% @context.group_category.groups.active.by_name.each do |group| %>
                  <li class="<%= 'active-selection' if group_homepage_pathfinder(group) %>"><%= link_to group.short_name, group_path(group) %></li>
                <% end %>
              </ul>

              <!-- this is so if there's more than 25 groups it doesn't immediately close the "Switch Group" menu when you open it, see: KNO-38 -->
              <script> document.getElementById('left-side').addEventListener('click', e => e.stopPropagation()) </script>
            <% end %>
            <% if @context && @context.respond_to?(:enrollment_term) && !@context.enrollment_term.default_term? %>
              <span id="section-tabs-header-subtitle" class="ellipsis"><%= @context.enrollment_term.name %></span>
            <% end %>
            <%= section_tabs %>
          <% end %>
        </div>
      <% end %>
      <div id="not_right_side" class="ic-app-main-content">
        <div id="content-wrapper" class="ic-Layout-contentWrapper">
          <%= render :partial => 'shared/content_notices' if @has_content_notices && @show_left_side %>
          <div id="content" class="ic-Layout-contentMain" role="main">
            <%= yield %>
          </div>
        </div>
        <div id="right-side-wrapper" class="ic-app-main-content__secondary">
          <aside id="right-side" role="complementary">
            <%= right_side %>
          </aside>
        </div>
      </div>
    </div>
    <% if @show_footer %>
      <%= render :partial => 'shared/canvas_footer' %>
    <% end %>
  </div>

  <% if @show_embedded_chat %>
    <%= render :partial => 'shared/embedded_chat' %>
  <% end %>

  <% if @show_fixed_bottom %>
    <%= render :partial => 'layouts/fixed_bottom' %>
  <% end %>

  <% if (wizard = (yield :wizard_box).presence) %>
    <div id="wizard_box" tabindex="-1">
      <div class="wizard_content">
        <div class="links">
          <a href="#" class="close_wizard_link"><i class="icon-x"></i><span class="screenreader-only"><%= t('links.close', 'Close') %></span></a>
        </div>
        <%= wizard %>
      </div>
    </div>
  <% end %>
  <% if (keyboard_navigation = (yield :keyboard_navigation).presence) %>
    <div id="keyboard_navigation">
      <%= keyboard_navigation %>
      <div class='hidden-readable' tabindex='0'>
        <%= t('keyboard_navigation.close', 'Press comma to close this dialog') %>
      </div>
    </div>
  <% end %>
    <div style="display:none;"><!-- Everything inside of this should always stay hidden -->
      <% if @context && session && temp_type = session["role_#{@context.asset_string}"] %>
        <span id="switched_role_type" class="<%= @context.asset_string %>" data-role="<%= temp_type %>"><%= Enrollment.readable_type(temp_type) %></span>
      <% end %>
      <% if @page_view %>
        <div id="page_view_id"><%= @page_view.id %></div>
      <% end %>
      <% if equella_enabled? %>
        <a id="equella_endpoint_url" href="<%= @equella_settings.endpoint %>">&nbsp;</a>
        <a id="equella_callback_url" href="<%= external_content_success_url('equella') %>">&nbsp;</a>
        <a id="equella_cancel_url" href="<%= external_content_cancel_url('equella') %>">&nbsp;</a>
        <a id="equella_action" href="<%= @equella_settings.default_action %>">&nbsp;</a>
        <% if @equella_settings.teaser %>
          <div id="equella_teaser"><%= @equella_settings.teaser %></div>
        <% end %>
      <% end %>
    </div>
  <div id='aria_alerts' class='hide-text affix' role="alert" aria-live="assertive"></div>
  <div id='StudentTray__Container'></div>
  <% if tutorials_enabled? %>
    <div class="NewUserTutorialTray__Container"></div>
  <% end %>
  <%= render :partial => 'layouts/foot', :locals => { :include_common_bundle => true } %>
</div> <!-- #application -->
</body>
</html>

htdocs/app/views/layouts/bare.html.erb
<%
# Copyright (C) 2012 - present Instructure, Inc.
#
# This file is part of Canvas.
#
# Canvas is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3 of the License.
#
# Canvas is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.
%>

<%= render :partial => "layouts/head" %>
<body>
<%= yield %>
<%= render :partial => 'layouts/foot', :locals => { :include_common_bundle => true } %>