htdocs/config/routes.rb
  get 'test_error' => 'info#test_error' unless Rails.env.production?

  concern :question_banks do
    resources :question_banks do
      post :bookmark
      post :reorder
      get :questions
      post :move_questions
      resources :assessment_questions
    end
  end

  concern :groups do
    resources :groups, except: :edit
    resources :group_categories, only: [:create, :update, :destroy]
    get 'group_unassigned_members' => 'groups#unassigned_members'
  end

  resources :group_categories do
    member do
      post 'clone_with_name'
    end
  end

  concern :files do
    resources :files, :except => [:new] do
      get 'inline' => 'files#text_show', as: :text_inline
      get 'download' => 'files#show', download: '1'
      get 'download.:type' => 'files#show', as: :typed_download, download: '1'
      get 'preview' => 'files#show', preview: '1'
      post 'inline_view' => 'files#show', inline: '1'
      get 'contents' => 'files#attachment_content', as: :attachment_content
      get 'file_preview' => 'file_previews#show'
      collection do
        get "folder#{full_path_glob}" => 'files#react_files', format: false
        get "search" => 'files#react_files', format: false
        get :quota
        post :reorder
      end
      get ':file_path' => 'files#show_relative', as: :relative_path, file_path: /.+/ #needs to stay below react_files route
    end
  end

  concern :file_images do
    get 'images' => 'files#images'
  end

  concern :relative_files do
    get 'file_contents/:file_path' => 'files#show_relative', as: :relative_file_path, file_path: /.+/
  end

  concern :folders do
    resources :folders
  end

  concern :media do
    get 'media_download' => 'users#media_download'
  end

  concern :users do
    get 'users' => 'context#roster'
    get 'user_services' => 'context#roster_user_services'
    get 'users/:user_id/usage' => 'context#roster_user_usage', as: :user_usage
    get 'users/:id' => 'context#roster_user', as: :user
  end

  concern :announcements do
    resources :announcements
    post 'announcements/external_feeds' => 'announcements#create_external_feed'
    delete 'announcements/external_feeds/:id' => 'announcements#destroy_external_feed', as: :announcements_external_feed
  end

  concern :discussions do
    resources :discussion_topics, only: [:index, :new, :show, :edit, :destroy]
    get 'discussion_topics/:id/:extras' => 'discussion_topics#show', as: :map, extras: /.+/
    resources :discussion_entries
  end

  concern :pages do
    resources :wiki_pages, path: :pages, except: [:update, :destroy, :new], constraints: { id: %r{[^\/]+} } do
      get 'revisions' => 'wiki_pages#revisions', as: :revisions
    end

    get 'wiki' => 'wiki_pages#front_page', as: :wiki
    get 'wiki/:id' => 'wiki_pages#show_redirect', id: /[^\/]+/
    get 'wiki/:id/revisions' => 'wiki_pages#revisions_redirect', id: /[^\/]+/
    get 'wiki/:id/revisions/:revision_id' => 'wiki_pages#revisions_redirect', id: /[^\/]+/
  end

  concern :conferences do
    resources :conferences do
      # rubocop:disable SymbolArray
      match :join, via: [:get, :post]
      match :close, via: [:get, :post]
      match :recording, via: [:get]
      match :recording, via: [:delete], to: 'conferences#delete_recording', as: :delete_recording
      # rubocop:enable SymbolArray
      get :settings
    end
  end

  get '/courses/:course_id/gradebook2', to: redirect('/courses/%{course_id}/gradebook')

  # There are a lot of resources that are all scoped to the course level
  # (assignments, files, wiki pages, user lists, forums, etc.).  Many of
  # these resources also apply to groups and individual users.  We call
  # courses, users, groups, or even accounts in this setting, "contexts".
  # There are some helper methods like the before_filter :get_context in application_controller
  # and the application_helper method :context_url to make retrieving
  # these contexts, and also generating context-specific urls, easier.
  resources :courses do
    # DEPRECATED
    get 'self_enrollment/:self_enrollment' => 'courses#self_enrollment', as: :self_enrollment
    post 'self_unenrollment/:self_unenrollment' => 'courses#self_unenrollment', as: :self_unenrollment
    post :unconclude
    get :students
    get 'observer_pairing_codes.csv', action: :observer_pairing_codes_csv, as: 'observer_pairing_codes'
    post :enrollment_invitation
    # this needs to come before the users concern, or users/:id will preempt it
    get 'users/prior' => 'context#prior_users', as: :prior_users
    concerns :users
    get :statistics
    delete 'unenroll/:id' => 'courses#unenroll_user', as: :unenroll
    post 'move_enrollment/:id' => 'courses#move_enrollment', as: :move_enrollment
    delete 'unenroll/:id.:format' => 'courses#unenroll_user', as: :formatted_unenroll
    post 'limit_user_grading/:id' => 'courses#limit_user', as: :limit_user_grading
    delete 'conclude_user/:id' => 'courses#conclude_user', as: :conclude_user_enrollment
    post 'unconclude_user/:id' => 'courses#unconclude_user', as: :unconclude_user_enrollment
    resources :sections, except: [:index, :edit, :new] do
      get 'crosslist/confirm/:new_course_id' => 'sections#crosslist_check', as: :confirm_crosslist
      post :crosslist
      delete 'crosslist' => 'sections#uncrosslist', as: :uncrosslist
    end

    get 'undelete' => 'context#undelete_index', as: :undelete_items
    post 'undelete/:asset_string' => 'context#undelete_item', as: :undelete_item

    get "settings#{full_path_glob}", action: :settings
    get :settings
    get 'details' => 'courses#settings'
    post :re_send_invitations
    post :enroll_users
    post :link_enrollment
    post :update_nav
    resource :gradebook do
      get 'submissions_upload/:assignment_id' => 'gradebooks#show_submissions_upload', as: :show_submissions_upload
      post 'submissions_upload/:assignment_id' => 'gradebooks#submissions_zip_upload', as: :submissions_upload

      collection do
        get :change_gradebook_version
        get :blank_submission
        get :final_grade_overrides
        get :speed_grader
        post :speed_grader_settings
        get :history
        post :update_submission
        post :change_gradebook_column_size
        post :save_gradebook_column_order
        get :user_ids
        get :grading_period_assignments
      end
    end

    resource :gradebook_csv, only: [:show]

    # DEPRECATED old migration emails pointed the user to this url, leave so the controller can redirect
    get 'imports/list' => 'content_imports#index', as: :import_list
    # DEPRECATED
    get 'imports' => 'content_imports#intro'
    resource :gradebook_upload do
      get 'data' => 'gradebook_uploads#data'
    end
    get 'grades' => 'gradebooks#grade_summary', id: nil
    get 'grading_rubrics' => 'gradebooks#grading_rubrics'
    get 'grades/:id' => 'gradebooks#grade_summary', as: :student_grades
    post 'save_assignment_order' => 'gradebooks#save_assignment_order', as: :save_assignment_order
    concerns :announcements
    get 'calendar' => 'calendars#show'
    get :locks
    concerns :discussions
    resources :assignments do
      get 'moderate' => 'assignments#show_moderate'

      get 'anonymous_submissions/:anonymous_id', to: 'submissions/anonymous_previews#show',
        constraints: ->(request) do
          request.query_parameters.key?(:preview) && request.format == :html
        end

      get 'anonymous_submissions/:anonymous_id', to: 'submissions/anonymous_downloads#show',
        constraints: ->(request) do
          request.query_parameters.key?(:download)
        end

      get 'anonymous_submissions/:anonymous_id', to: 'anonymous_submissions#show', as: :anonymous_submission

      get 'submissions/:id', to: 'submissions/previews#show',
        constraints: ->(request) do
          request.query_parameters.key?(:preview) && request.format == :html
        end

      get 'submissions/:id', to: 'submissions/downloads#show',
        constraints: ->(request) do
          request.query_parameters.key?(:download)
        end

      put 'anonymous_submissions/:anonymous_id', to: 'anonymous_submissions#update'
      resources :submissions do
        get 'originality_report/:asset_string' => 'submissions#originality_report', as: :originality_report
        post 'turnitin/resubmit' => 'submissions#resubmit_to_turnitin', as: :resubmit_to_turnitin
        get 'turnitin/:asset_string' => 'submissions#turnitin_report', as: :turnitin_report
        post 'vericite/resubmit' => 'submissions#resubmit_to_vericite', as: :resubmit_to_vericite
        get 'vericite/:asset_string' => 'submissions#vericite_report', as: :vericite_report
        get 'audit_events' => 'submissions#audit_events', as: :audit_events
      end

      get 'anonymous_submissions/:anonymous_id/originality_report/:asset_string',
        to: 'anonymous_submissions#originality_report',
        as: :anonymous_submission_originality_report
      post 'anonymous_submissions/:anonymous_id/turnitin/resubmit',
        to: 'anonymous_submissions#resubmit_to_turnitin',
        as: :anonymous_submission_resubmit_to_turnitin
      get 'anonymous_submissions/:anonymous_id/turnitin/:asset_string',
        to: 'anonymous_submissions#turnitin_report',
        as: :anonymous_submission_turnitin_report
      post 'anonymous_submissions/:anonymous_id/vericite/resubmit',
        to: 'anonymous_submissions#resubmit_to_vericite',
        as: :anonymous_submission_resubmit_to_vericite
      get 'anonymous_submissions/:anonymous_id/vericite/:asset_string',
        to: 'anonymous_submissions#vericite_report',
        as: :anonymous_submission_vericite_report

      get :rubric
      resource :rubric_association, path: :rubric do
        resources :rubric_assessments, path: :assessments
      end

      get :peer_reviews
      post :assign_peer_reviews
      delete 'peer_reviews/:id' => 'assignments#delete_peer_review', as: :delete_peer_review

htdocs/app/helpers/courses_helper.rb
#
# Copyright (C) 2011 - present Instructure, Inc.
#
# This file is part of Canvas.
#
# Canvas is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3 of the License.
#
# Canvas is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.
#

module CoursesHelper
  def icon_data(opts = {})
    context      = opts[:context]
    contexts     = opts[:contexts]
    current_user = opts[:current_user]
    recent_event = opts[:recent_event]
    submission   = opts[:submission]
    student_only = opts[:student_only]
    show_assignment_type_icon = opts[:show_assignment_type_icon]

    return [nil, "Quiz", 'icon-quiz'] if recent_event.is_a?(Quizzes::Quiz)
    return [nil, "Event", "icon-calendar-day"] unless recent_event.is_a?(Assignment)

    event_type = ['Assignment', 'icon-assignment']
    event_type = ['Quiz', 'icon-quiz'] if recent_event.submission_types == 'online_quiz'
    event_type = ['Discussion', 'icon-discussion'] if recent_event.submission_types == 'discussion_topic'

    # because this happens in a sidebar, the context may be wrong. check and fix
    # it if that's the case.
    context = context.class == recent_event.class && context.id == recent_event.context_id ?
      context : recent_event.context

    icon_data = [nil] + event_type

    if can_do(context, current_user, :participate_as_student)
      if submission && submission.workflow_state != 'unsubmitted'
        event_type = ['', 'icon-check'] unless show_assignment_type_icon
        icon_data = [submission.readable_state] + event_type
      else
        icon_data = [t('#courses.recent_event.not_submitted', 'not submitted')] + event_type
      end
      icon_data[0] = nil if !recent_event.expects_submission?
    elsif !student_only && can_do(context, current_user, :manage_grades)
      # no submissions
      if !recent_event.has_submitted_submissions?
        icon_data = [t('#courses.recent_event.no_submissions', 'no submissions')] + event_type
      # all received submissions graded (but not all turned in)
      elsif recent_event.submitted_count < context.students.size &&
        !current_user.assignments_needing_grading(:contexts => contexts).include?(recent_event)
        icon_data = [t('#courses.recent_event.no_new_submissions', 'no new submissions')] + event_type
      # all submissions turned in and graded
      elsif !current_user.assignments_needing_grading(:contexts => contexts).include?(recent_event)
        icon_data = [t('#courses.recent_event.all_graded', 'all graded')] + event_type
      # assignments need grading
      else
        icon_data = [t('#courses.recent_event.needs_grading', 'needs grading')] + event_type
      end
    end

    icon_data
  end

  def recent_event_url(recent_event)
    context = recent_event.context
    if recent_event.is_a?(Assignment)
      url = context_url(context, :context_assignment_url, :id => recent_event.id)
    else
      url = calendar_url_for(nil, {
        :query => {:month => recent_event.start_at.month, :year => recent_event.start_at.year},
        :anchor => "calendar_event_" + recent_event.id.to_s
      })
    end

    url
  end

  # Public: Display the given user count, or "None" if it's 0.
  #
  # count - The count to display (e.g. 7)
  #
  # Returns a text string.
  def user_count(count)
    count == 0 ? t('#courses.settings.none', 'None') : count
  end

  # Public: check for permission on a new course
  #
  # Sometimes we need to look up a course permission without having a course to
  # reference. In that case it suffices to temporarily scaffold-up a course and
  # teacher enrollment in order to be able to ask the permission system about a
  # course permission. The default account is the one most useful for permissions
  # questions arising from new course creation.
  def course_permission_to?(perm_name, account = nil)
    account ||= @domain_root_account.manually_created_courses_account
    course = Course.new(account_id: account.id)
    TeacherEnrollment.new(user: @current_user, course: course)
    account.grants_right?(@current_user, perm_name.to_sym)
  end

  def readable_grade(submission)
    if submission.grade and
       submission.workflow_state == 'graded'
      if submission.grading_type == 'points' and
         submission.assignment and
         submission.assignment.respond_to?(:points_possible)
         score_out_of_points_possible(submission.grade, submission.assignment.points_possible)
      else
        i18n_grade(submission.grade, submission.grading_type).to_s
      end
    end
  end

  def skip_custom_role?(cr)
    cr[:count] == 0 && cr[:workflow_state] == 'inactive'
  end

  def user_type(course, user, enrollments = nil)
    enrollment = enrollments ? enrollments[user.id] : course.enrollments.find_by(user: user)

    if enrollment.nil?
      return course.account_membership_allows(user) ? "admin" : nil
    end

    type = enrollment.type.remove(/Enrollment/).downcase
    type = "student" if %w/studentview observer/.include?(type)

    type
  end
  module_function :user_type

  def why_cant_i_enable_master_course(course)
    return nil if MasterCourses::MasterTemplate.is_master_course?(course)

    if MasterCourses::ChildSubscription.is_child_course?(course)
      t('Course is already associated with a blueprint')
    elsif course.student_enrollments.not_fake.exists?
      t("Cannot have a blueprint course with students")
    else
      nil
    end
  end
end

htdocs/app/views/courses/_group_list.html.erb
<%
# Copyright (C) 2011 - present Instructure, Inc.
#
# This file is part of Canvas.
#
# Canvas is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3 of the License.
#
# Canvas is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.
%>

<% if group_list && !group_list.empty? %>
  <h2><%= t('headings.groups', %{Course Groups}) %></h2>
  <ul class="unstyled_list group_list" %>
    <% group_list.each do |group| %>
      <li><%= link_to group.name, group_path(group.id) %></li>
    <% end %>
  </ul>
<% end %>

htdocs/app/views/courses/show.html.erb
<%
# Copyright (C) 2011 - present Instructure, Inc.
#
# This file is part of Canvas.
#
# Canvas is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3 of the License.
#
# Canvas is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.
%>

<% provide :page_title, @context.name %>

<h1 class='screenreader-only'><%= @context.name %></h1>

<% provide :right_side do %>
  <div id="course_show_secondary">
    <% @can_manage = can_do(@context, @current_user, :manage) %>
    <% @module_dnd_FF = @domain_root_account.feature_enabled?(:module_dnd) %>
    <% @can_create_announcements = @context.announcements.temp_record.grants_right?(@current_user, session, :create) %>
    <% if can_do(@context, @current_user, :change_course_state) && (@context.unpublished? || @context.unpublishable?) %>
      <div id="course_status">
        <h3>
          <%= t('headers.course_status', %{Course Status}) %>
        </h3>
        <div id='course_status_actions' class="ui-buttonset">
          <%= form_for @context, html: {id: "course_status_form"} do |f| %>
            <% if @context.created? || @context.claimed? %>
              <button type="button" class='ui-button btn-unpublish disabled' disabled>
                <i class="icon-unpublish"></i><%= t('#buttons.unpublished', %{Unpublished}) %>
              </button>
              <button type='submit' class="ui-button btn-publish">
                <i class="icon-publish icon-Solid"></i><%= t('#buttons.publish', %{Publish}) %>
              </button>
              <input type='hidden' name='course[event]' value='offer' />
            <% else %>
              <button type='submit' class="ui-button">
                <i class="icon-unpublish"></i>&nbsp;<%= t('#buttons.unpublish', %{Unpublish}) %>
              </button>
              <button type="button" class="ui-button disabled btn-published" disabled>
                <i class="icon-publish icon-Solid"></i><%= t('#buttons.published', %{Published}) %>
              </button>
              <input type='hidden' name='course[event]' value='claim' />
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>

    <% if @module_dnd_FF && can_do(@context, @current_user, :manage_content) %>
      <a class="btn button-sidebar-wide" href="<%= context_url(@context, :context_content_migrations_url) %>">
        <i class="icon-import"></i>
        <%= t('links.import', %{Import Existing Content}) %>
      </a>
    <% end %>

    <% if @can_manage || @can_create_announcements || @course_home_view != 'feed' || @course_home_sub_navigation_tools.present? %>
      <div class="course-options">
        <%= external_tools_menu_items(@course_home_sub_navigation_tools, {link_class: "btn button-sidebar-wide course-home-sub-navigation-lti", settings_key: :course_home_sub_navigation}) %>
        <% if @can_manage %>
          <div id="choose_home_page"></div>
          <div id="choose_home_page_not_modules"></div>
        <% end %>

        <% if @course_home_view != 'feed' %>
          <a class="btn button-sidebar-wide" href="<%= context_url(@context, :context_url, :view => 'feed') %>">
            <i class="icon-stats"></i>
            <%= t('links.view_course_stream', %{View Course Stream}) %>
          </a>
        <% end %>

        <% if @can_manage && !@domain_root_account.try(:feature_enabled?, :new_user_tutorial) %>
          <script>
            Object.assign(
              ENV,
              <%= raw StringifyIds.recursively_stringify_ids({
                COURSE_WIZARD: {
                  just_saved: @context_just_saved,
                  checklist_states: {
                    import_step: !@context.attachments.active.exists?,
                    assignment_step: !@context.assignments.active.exists?,
                    add_student_step: !@context.students.exists?,
                    navigation_step: @context.tab_configuration.empty?,
                    home_page_step: true,
                    # The current wizard just always marks this as complete.
                    calendar_event_step: !@context.calendar_events.active.exists?,
                    add_ta_step: !@context.tas.exists?,
                    publish_step: @context.workflow_state === 'available'
                  },
                  urls: {
                    content_import: context_url(@context, :context_content_migrations_url),
                    add_assignments: context_url(@context, :context_assignments_url, wizard: 1),
                    add_students: course_users_path(course_id: @context),
                    add_files: context_url(@context, :context_files_url, wizard: 1),
                    select_navigation: context_url(@context, :context_details_url),
                    course_calendar: calendar_path(course_id: @context),
                    add_tas: course_users_path(course_id: @context),
                    publish_course: course_path(@context)
                  },
                  permissions: {
                    # Sending the permissions just so maybe later we can extract this easier.
                    can_manage_content: can_do(@context, @current_user, :manage_content),
                    can_manage_students: can_do(@context, @current_user, :manage_students),
                    can_manage_assignments: can_do(@context, @current_user, :manage_assignments),
                    can_manage_files: can_do(@context, @current_user, :manage_files),
                    can_update: can_do(@context, @current_user, :update),
                    can_manage_calendar: can_do(@context, @current_user, :manage_calendar),
                    can_manage_admin_users: can_do(@context, @current_user, :manage_admin_users),
                    can_change_course_state: can_do(@context, @current_user, :change_course_state)
                  }
                }
              }).to_json %>
            )
          </script>

          <% js_bundle :course_wizard %>
          <% css_bundle :course_wizard %>
          <a href="#" class="btn button-sidebar-wide wizard_popup_link  <%= 'auto_open' if @context.created? || @context.claimed? %>">
            <i class="icon-question"></i> <%= t('links.course_setup', %{Course Setup Checklist}) %>
          </a>
        <% end %>

        <% if @can_create_announcements %>
          <a class="btn button-sidebar-wide" href="<%= context_url(@context, :new_context_discussion_topic_url, :is_announcement => true) %>"><i class="icon-announcement"></i> <%= t('links.new_announcement', %{New Announcement}) %>
          </a>
        <% end %>

        <% if can_do(@context, @current_user, :use_student_view) %>
          <%= link_to course_student_view_path(@context), :method => :post, :class => 'btn button-sidebar-wide' do %>
            <i class="icon-student-view"></i> <%= t('links.student_view', 'Student View') %>
          <% end %>
        <% end %>

        <% course_custom_links.each do |link| %>
          <a class="btn button-sidebar-wide" href="<%= link[:url] %>"><i class="<%= link[:icon_class] %>" role="presentation"></i> <%= link[:text] %></a>
        <% end %>
      </div>
    <% end %>

    <% if @context.available? && @context.self_enrollment_enabled? && @context.open_enrollment && (!@context_enrollment || !@context_enrollment.active?) %>
      <a href="<%= enroll_url(@context.self_enrollment_code) %>" class="btn button-sidebar-wide self_enrollment_link">
        <i class="icon-user-add"></i>
        <%= t('links.join_course', %{Join this Course}) %>
      </a>
    <% elsif @context_enrollment && @context_enrollment.self_enrolled && @context_enrollment.active? %>
      <a href="#" class="btn button-sidebar-wide self_unenrollment_link">
        <i class="icon-end"></i>
        <%= t('links.drop_course', %{Drop this Course}) %>
      </a>
      <div id="self_unenrollment_dialog" style="display: none;">
        <h2><i class="icon-warning"></i> <%= t('headings.confirm_unenroll', %{Confirm Unenrollment}) %></h2>
        <%= t('details.confirm_unenroll', %{Are you sure you want to unenroll in this course?  You will no longer be able to see the course roster or communicate directly with the teachers, and you will no longer see course events in your stream and as notifications.}) %>
        <div class="button-container">
          <a href="<%= course_self_unenrollment_path(@context, @context_enrollment.uuid) %>" class="btn btn-primary action"><i class="icon-end"></i> <span><%= t('links.drop_course', %{Drop this Course}) %></span></a>
          <a href="#" class="btn dialog_closer"><%= t('#buttons.cancel', %{Cancel}) %></a>
        </div>
      </div>
    <% end %>

    <% if @context_enrollment&.student? %>
      <a class="btn button-sidebar-wide" href="<%= calendar_url_for(@context) %>">
        <i class="icon-calendar-day"></i>
        <%= t('links.view_course_calendar', %{View Course Calendar}) %>
      </a>
    <% end %>

    <% if @context_enrollment && @domain_root_account.try(:feature_enabled?, :mute_notifications_by_course) %>
      <a class="btn button-sidebar-wide" href="<%= context_url(@context, :context_url, :view => 'notifications') %>">
        <i class="icon-<%= @course_notifications_enabled ? "unmuted" : "muted" %>"></i>
        <%= t('links.view_course_notification_settings', %{View Course Notifications}) %>
      </a>
    <% end %>

    <%= render :partial => 'to_do_list', :locals => {:contexts => [@context], :show_legacy_todo_list => !@context_enrollment&.student?} %>
    <%= render :partial => "group_list", :locals => {:group_list => @user_groups} %>
    <%= nbsp unless @current_user %>
  </div>
  <% if @course_home_view == 'assignments' %>
    <%= render :partial => 'assignments/assignments_list_right_side', :locals => {:course_home => true} %>
  <% elsif @course_home_view == 'syllabus' %>
    <%= render :partial => 'assignments/syllabus_right_side', :locals => {:course_home => true} %>
  <% elsif !@context_enrollment&.student? %>
    <% locals = {:title => t("Coming Up"), :contexts_to_link_to => @context, :upcoming => true, :period => :one_week} %>
    <% if @current_user %>
      <% cache([@current_user, safe_cache_key(@contexts), 'course_upcoming_events' ].cache_key) do %>
        <%
          events = @current_user.upcoming_events(:contexts => @contexts)
          assignments = events.select{|e| e.is_a?(Assignment)}
          @current_user_submissions = Submission.where(:assignment_id => assignments, :user_id => @current_user).to_a if assignments.any?
        %>
        <%= render :partial => "shared/event_list", :object => events, :locals => locals %>
      <% end %>
    <% else %>
      <%= render :partial => "shared/event_list", :object => [], :locals => locals %>
    <% end %>
  <% end %>
  <% if @show_recent_feedback %>
    <%= render :partial => "shared/event_list", :object => @recent_feedback, :locals => {:title => t('titles.recent_feedback', "Recent Feedback"), :contexts_to_link_to => @context, :is_recent_feedback => true} %>
  <% end %>
<% end %>

<% if @pending_enrollment %>
  <%= render :partial => 'shared/dashboard_invitation', :object => @pending_enrollment %>
<% end %>

<% if @context.show_announcements_on_home_page? %>
  <div id="announcements_on_home_page"></div>
  <% js_bundle :announcements_on_home_page %>
<% end %>
<div id="course_home_content">
  <% if @course_home_view == 'wiki' %>
    <div id="wiki_page_show"></div>
  <% elsif @course_home_view == 'modules' %>
    <%= render :partial => 'context_modules/content_next', :locals => {:course_home => true} %>
  <% elsif @course_home_view == 'assignments' %>
  <% elsif @course_home_view == 'syllabus' %>
    <%= render :partial => 'assignments/syllabus_content', :locals => {:course_home => true} %>
  <% else %>
    <%= render :partial => 'shared/dashboard_messages' %>
    <%= render :partial => 'shared/recent_activity' %>
  <% end %>
</div>
<% if @context.public_license? %>
  <div class="public-license" style="margin-top: 20px;">

    <a class="public-license-image-link" href="<%= @context.license_url %>"><%= image_tag "cc/#{@context.license}.png", :alt => @context.readable_license   %></a>
    <span class="public-license-text"><%= t 'license_notice', %{This course content is offered under a %{license_type} license.  Content in this course can be considered under this license unless otherwise noted.}, :license_type => content_tag('b', link_to(@context.readable_license, @context.license_url)) %></span>
    <div class="clear"></div>
  </div>
<% end %>
<div id="wizard_box"></div>